version: "3"
services:
  cells:
    image: pydio/cells:latest
    restart: ${RESTART}
    ports: ["8080:8080"]
    environment:
      - CELLS_BIND=${CELLS_BIND}
      - CELLS_EXTERNAL=${CELLS_EXTERNAL}
    volumes:
      - "cellsdir:/var/cells"
      - "data:/var/cells/data"

  db:
    image: mariadb:10.4
    restart: ${RESTART}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command:
      [
        mysqld,
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_unicode_ci,
      ]
    volumes:
      - "mysqldir:/var/lib/mysql"

volumes:
  data: {}
  cellsdir: {}
  mysqldir: {}
